### ISSUE TITLE
Saving the meta graph

### ISSUE THREAD

**Issue by AakashKumarNain** [jonrei/tf-AdaIN#4]
How should I save the meta graph once I run the code? If I use `tf.train.Saver()` object to save the session, then it throws an error saying `No variables to save`. Any idea how to save the meta graph?

**Comment by jonrei** [comment]
Could you provide a code sample where you try to save the graph?

**Comment by cicido** [comment]
tf.train.write_graph(sess.graph_def, "", "model1.pb", False)

**Comment by cicido** [comment]
there is no variables, only constants.  We do only forward propagation once and without back propagation
--

**Comment by cicido** [comment]
not train, only inference
