### ISSUE TITLE
CPU mode

### ISSUE THREAD

**Issue by CJHFUTURE** [jonrei/tf-AdaIN#7]
Great implementaion! 
Is it possible to run in CPU mode only?

**Comment by jonrei** [comment]
It should run on CPU only out of the box if no GPU is available, but haven't tried it. Might need some flags like:
     
    AdaIN.py:138: with tf.Graph().as_default() as g, tf.Session(graph=g, config=tf.ConfigProto(device_count={'GPU': 0})) as sess, tf.variable_scope(tf.get_variable_scope(), reuse=False) as scope:
